Web/Controllers/agencyController.cs
using Services.Domain.Admin;
using Services.DomainServices.Account;
using Services.DomainServices.Admin;
using Services.DomainServices.Common;
using Services.EmailService;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.AppCode;

namespace Web.Controllers
{
    public class agencyController : BaseController
    {
        // GET: agency
        private readonly CommonDomainService _commonDomainService;
        public readonly AdminDomainService _adminDomainService;
        public readonly AccountDomainService _accountDomainService;
        public agencyController(AdminDomainService adminDomainService, CommonDomainService commonDomainService, AccountDomainService accountDomainService)
        {
            _adminDomainService = adminDomainService;
            _commonDomainService = commonDomainService;
            _accountDomainService = accountDomainService;

        }


        [ActionName("about-us")]
        public ActionResult About()
        {
            ViewBag.SiteSetting = _commonDomainService.GetSiteSettingsData();
            return View("~/Views/home/About.cshtml");
        }

        [ActionName("clear-everything")]
        public ActionResult ClearEverithing()
        {
            StudentTicketBookingList.TicketEntityInSession = null;
            StudentTicketBookingList.CustomerEntityInSession = null;

            string baseUrl = Request.Url.Scheme + "://" + Request.Url.Authority +
                       Request.ApplicationPath.TrimEnd('/') + "/";
            string urlLink = baseUrl + "agency/student-service";
            return Redirect(urlLink);
        }

        [ActionName("contact-us")]
        public ActionResult Contact()
        {
            ViewBag.SiteSetting = _commonDomainService.GetSiteSettingsData();
            ViewBag.OurServiceProviders = _commonDomainService.GetContactPageServiceProviders();
            return View("~/Views/home/Contact.cshtml");
        }

        [ActionName("question-answer")]
        public ActionResult FAQ()
        {
            ViewBag.SiteSetting = _commonDomainService.GetSiteSettingsData();
            return View("~/Views/home/FAQ.cshtml");
        }

        [ActionName("terms-conditions")]
        public ActionResult TermsAndConditions()
        {
            ViewBag.SiteSetting = _commonDomainService.GetSiteSettingsData();
            return View("~/Views/home/TermsAndConditions.cshtml");
        }

        [ActionName("our-agents")]
        public ActionResult OurAgents()
        {
            ViewBag.OurAgentList= _adminDomainService.GetVendorListForAdmin();
            return View("~/Views/home/OurAgents.cshtml");
        }

        [ActionName("privacy-policy")]
        public ActionResult PrivacyPolicy()
        {
            ViewBag.SiteSetting = _commonDomainService.GetSiteSettingsData();
            return View("~/Views/home/PrivacyPolicy.cshtml");
        }

        [ActionName("feedback")]
        public ActionResult FeedBack()
        {
            
            return View("~/Views/home/FeedBack.cshtml");
        }

        [ActionName("customer-information")]
        public ActionResult CustomerInformation()
        {
            if (StudentTicketBookingList.TicketEntityInSession == null)
            {
                string baseUrl = Request.Url.Scheme + "://" + Request.Url.Authority +
                       Request.ApplicationPath.TrimEnd('/') + "/";
                string urlLink = baseUrl + "agency/student-service";
                return Redirect(urlLink);
            }
            else
            {
                string busNumber = "";
                int totalSeat = 0;
                int totalPrice = 0;
                string pricePerDet = "";
                string returnPrice = "";
                string eqPrice = "";

                foreach (SingleTicketPurchase loopItem in StudentTicketBookingList.TicketEntityInSession) {

                    if (busNumber == "")
                        busNumber = loopItem.BusNumber;
                    else
                        busNumber = busNumber + ", " + loopItem.BusNumber;

                    if (busNumber == "")
                        busNumber = loopItem.BusNumber;

                    totalSeat += loopItem.SeatCount;
                    totalPrice += loopItem.TotalSeatPrice;
                    if (pricePerDet == "")
                        pricePerDet = "(" + loopItem.PricePerSeat.ToString() + " * " + loopItem.SeatCount.ToString() + ")";
                    else
                        pricePerDet = pricePerDet + " (" + loopItem.PricePerSeat.ToString() + " * " + loopItem.SeatCount.ToString() + ")";

                    List<TimeSchedule> data = new List<TimeSchedule>();
                    if (loopItem.ReturnedDate != null && loopItem.ReturnedDate != "")
                    {
                        data = _accountDomainService.GetBusTimeScheduleListByFromAndToId(loopItem.toId, StudentTicketBookingList.TicketEntityInSession[0].fromId).ToList();


                        if (data != null && data.Count > 0)
                        {
                            int rP = (data[0].RatePerSeat * loopItem.SeatCount);
                            returnPrice = rP.ToString();
                            eqPrice = (loopItem.TotalSeatPrice + rP).ToString();
                        }
                        else {
                            int rP = (750 * loopItem.SeatCount);
                            returnPrice = rP.ToString();
                            eqPrice = (loopItem.TotalSeatPrice + rP).ToString();
                        }

                    }
                    
                }

                ViewBag.BusNumbers = busNumber;
                ViewBag.TotalSeat = totalSeat.ToString();
                if (returnPrice != "")
                    ViewBag.TotalPrice = totalPrice.ToString() + " + " + returnPrice + " = " + eqPrice;
                else
                    ViewBag.TotalPrice = totalPrice.ToString();

                if (returnPrice != "")
                    ViewBag.PricePerLoop = pricePerDet + " (return = " + returnPrice + ")";
                else
                    ViewBag.PricePerLoop = pricePerDet;

                return View("~/Views/home/CustomerInformation.cshtml");
            }
           
        }

        [ActionName("ticket-details")]
        public ActionResult TicketDetails()
        {
            if (StudentTicketBookingList.TicketEntityInSession == null || StudentTicketBookingList.CustomerEntityInSession == null)
            {
                string baseUrl = Request.Url.Scheme + "://" + Request.Url.Authority +
                       Request.ApplicationPath.TrimEnd('/') + "/";
                string urlLink = baseUrl + "agency/student-service";
                return Redirect(urlLink);
            }
            else
            {
                string busNumber = "";
                int totalSeat = 0;
                int totalPrice = 0;
                string pricePerDet = "";
                string source = "";
                string destination = "";
                string seatNumbers = "";
                string tourDates = "";
                string returnDate = "";
                string TravelTimes = "";
                string returnPrice = "";
                string eqPrice = "";
                foreach (SingleTicketPurchase loopItem in StudentTicketBookingList.TicketEntityInSession)
                {
                    if (busNumber == "")
                        busNumber = loopItem.BusNumber;
                    else
                        busNumber = busNumber + ", " + loopItem.BusNumber;

                    if (tourDates == "")
                        tourDates = loopItem.TourDate;
                    else
                        tourDates = tourDates + ", " + loopItem.TourDate;

                    if (TravelTimes == "")
                        TravelTimes = loopItem.startTime;
                    else
                        TravelTimes = TravelTimes + ", " + loopItem.startTime;
                    
                    if (source == "")
                        source = loopItem.TourRoot;
                    else
                        source = source + ", " + loopItem.TourRoot;

                    if (destination == "")
                        destination = loopItem.Destination;
                    else
                        destination = destination + ", " + loopItem.Destination;

                    if (seatNumbers == "")
                        seatNumbers = "(" + loopItem.SeatNumbers + ")";
                    else
                        seatNumbers = seatNumbers + " - " + "(" + loopItem.SeatNumbers + ")";


                    totalSeat += loopItem.SeatCount;
                    totalPrice += loopItem.TotalSeatPrice;
                    eqPrice = totalPrice.ToString();
                    if (pricePerDet == "")
                        pricePerDet = "(" + loopItem.PricePerSeat.ToString() + " * " + loopItem.SeatCount.ToString() + ")";
                    else
                        pricePerDet = pricePerDet + ", (" + loopItem.PricePerSeat.ToString() + " * " + loopItem.SeatCount.ToString() + ")";

                    if (loopItem.ReturnedDate != null && loopItem.ReturnedDate != "")
                    {
                        List<TimeSchedule> data = new List<TimeSchedule>();
                        if (returnDate == "")
                        {
                            returnDate = loopItem.ReturnedDate;
                            data = _accountDomainService.GetBusTimeScheduleListByFromAndToId(loopItem.toId, StudentTicketBookingList.TicketEntityInSession[0].fromId).ToList();


                            if (data != null && data.Count > 0)
                            {
                                int rP = (data[0].RatePerSeat * loopItem.SeatCount);
                                returnPrice = rP.ToString();

Web/Controllers/homeController.cs
using Services.Domain.Admin;
using Services.Domain.SuperAdmin;
using Services.DomainServices.Admin;
using Services.DomainServices.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.AppCode;

namespace Web.Controllers
{
    public class homeController : BaseController
    {

        private readonly SliderDomainService _sliderDomainService;
        private readonly BlogDomainService _blogDomainService;
        private readonly CommonDomainService _commonDomainService;
        //private readonly ProductDomainService _productDomainService;
        public homeController(SliderDomainService sliderDomainService, BlogDomainService blogDomainService, CommonDomainService commonDomainService)
        {

            _sliderDomainService = sliderDomainService;
            _blogDomainService = blogDomainService;
            _commonDomainService = commonDomainService;
            //_productDomainService = productDomainService;

        }
        public ActionResult Index()
        {
            ViewBag.SiteSetting = _commonDomainService.GetSiteSettingsData();
            ViewBag.AdvantageList = _commonDomainService.GetHomePageAdvantageLists();
            ViewBag.OurServiceProviders = _commonDomainService.GetHomePageServiceProviders();
            return View();
        }
     
        public ActionResult InternalServerError()
        {
            return View("~/Views/ErrorPage/InternalServerError.cshtml");
        }
        
        public PartialViewResult _LoadMainSlider(SiteSettingsTable siteSettings)
        {
            
            ViewBag.MainSlider = _sliderDomainService.GetMainSlider();
            return PartialView("~/Views/Partial/home/HomeMainSlider.cshtml");
        }

        public PartialViewResult _LoadHomePageBlog()
        {
            ViewBag.AllPostList = _blogDomainService.GetAllBlogPostList();
            return PartialView("~/Views/Partial/home/HomeTwoPost.cshtml");
        }
        
        public PartialViewResult _LoadMainMenu()
        {
            ViewBag.SiteSetting = _commonDomainService.GetSiteSettingsData();
            return PartialView("~/Views/Partial/Menus/TopMainMenu.cshtml");
        }

        public PartialViewResult _LoadWebSiteFooter()
        {
            ViewBag.SiteSetting = _commonDomainService.GetSiteSettingsData();
            return PartialView("~/Views/Partial/home/WebSiteFooter.cshtml");
        }

    }
}

Web/Views/Partial/home/BestSellerTab.cshtml
<div class="bestsell-pro">
    <div>
        <div class="slider-items-products">
            <div class="bestsell-block">
                <div class="block-title">
                    <h2>Best Sellers</h2>
                </div>
                <div id="bestsell-slider" class="product-flexslider hidden-buttons">
                    <div class="slider-items slider-width-col4 products-grid block-content">
                        @if (ViewBag.BestSellerProduct != null && ViewBag.BestSellerProduct.Count > 0)
                        {
                            for (int item = 0; item < ViewBag.BestSellerProduct.Count; item++)
                            {
                                <div class="item">
                                    <div class="item-inner">
                                        <div class="item-img">
                                            <div class="item-img-info">
                                                <a href="~/product/details/@ViewBag.BestSellerProduct[item].ProductId" title="@ViewBag.BestSellerProduct[item].Name" class="product-image"><img src="@Url.Content("~/" + ViewBag.BestSellerProduct[item].ImageURL)" alt="@ViewBag.BestSellerProduct[item].Name"></a>
                                                @*<div class="new-label new-top-left">New</div>*@
                                                <div class="box-hover">
                                                    <ul class="add-to-links">
                                                        <li><a class="link-quickview" href="~/product/details/@ViewBag.BestSellerProduct[item].ProductId"></a></li>
                                                        <li><a class="link-wishlist" href="wishlist.html"></a></li>
                                                        <li><a class="link-compare" href="compare.html"></a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="item-info">
                                            <div class="info-inner">
                                                <div class="item-title"> <a title="Retis lapen casen" href="~/product/details/@ViewBag.BestSellerProduct[item].ProductId"> @ViewBag.BestSellerProduct[item].Name </a> </div>
                                                <div class="item-content">
                                                    <div class="rating">
                                                        <div class="ratings">
                                                            @if (ViewBag.BestSellerProduct[item].Rating >= 2 && ViewBag.BestSellerProduct[item].Rating <= 2.7M)
                                                            {
                                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                                <i class="fa fa-star-half-o" aria-hidden="true"></i>
                                                                <i class="fa fa-star-o" aria-hidden="true"></i>
                                                                <i class="fa fa-star-o" aria-hidden="true"></i>
                                                            }
                                                            else if (ViewBag.BestSellerProduct[item].Rating > 2.7M && ViewBag.BestSellerProduct[item].Rating <= 3.2M)
                                                            {
                                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                                <i class="fa fa-star-o" aria-hidden="true"></i>
                                                                <i class="fa fa-star-o" aria-hidden="true"></i>
                                                            }
                                                            else if (ViewBag.BestSellerProduct[item].Rating > 3.2M && ViewBag.BestSellerProduct[item].Rating <= 3.7M)
                                                            {
                                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                                <i class="fa fa-star-half-o" aria-hidden="true"></i>
                                                                <i class="fa fa-star-o" aria-hidden="true"></i>
                                                            }
                                                            else if (ViewBag.BestSellerProduct[item].Rating > 3.7M && ViewBag.BestSellerProduct[item].Rating <= 4.2M)
                                                            {
                                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                                <i class="fa fa-star-o" aria-hidden="true"></i>
                                                            }
                                                            else if (ViewBag.BestSellerProduct[item].Rating > 4.2M && ViewBag.BestSellerProduct[item].Rating <= 4.7M)
                                                            {
                                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                                <i class="fa fa-star-half-o" aria-hidden="true"></i>
                                                            }
                                                            else if (ViewBag.BestSellerProduct[item].Rating > 4.7M && ViewBag.BestSellerProduct[item].Rating <= 6)
                                                            {
                                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                            }
                                                            <p class="rating-links"> <a href="#">1 Review(s)</a> <span class="separator">|</span> <a href="#">Add Review</a> </p>
                                                        </div>
                                                    </div>
                                                    <div class="item-price">
                                                        <div class="price-box">
                                                            @if (ViewBag.BestSellerProduct[item].OldPrice != null)
                                                            {
                                                                <p class="old-price"><span class="price-label">Regular Price:</span> <span class="price">$@ViewBag.BestSellerProduct[item].OldPrice </span> </p>
                                                                <p class="special-price"><span class="price-label">Special Price</span> <span class="price">$@ViewBag.BestSellerProduct[item].Price </span> </p>
                                                            }
                                                            else
                                                            {
                                                                <span class="regular-price"><span class="price">$@ViewBag.BestSellerProduct[item].Price</span> </span>
                                                            }

                                                        </div>
                                                    </div>
                                                    <div class="action">
                                                        <button class="button btn-cart" type="button" title="Add to Cart" pid="@ViewBag.BestSellerProduct[item].ProductId" data-original-title="Add to Cart"><span>Add to Cart</span></button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>

                            }
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Web/Views/Partial/home/HomeMainSlider.cshtml
@if (ViewBag.MainSlider != null && ViewBag.MainSlider.Count > 0)
{


    <div id="magik-slideshow" class="magik-slideshow slider-block">
        <div id='rev_slider_4_wrapper' class='rev_slider_wrapper fullwidthbanner-container'>
            <div id='rev_slider_4' class='rev_slider fullwidthabanner'>
                <ul>
                    @for (var itemCount = 0; itemCount < ViewBag.MainSlider.Count; itemCount++)
                {
                        <li data-transition='random' data-slotamount='7' data-masterspeed='1000' data-thumb='@Url.Content("~" + ViewBag.MainSlider[itemCount].ImagePath)'>
                            <img src='@Url.Content("~" + ViewBag.MainSlider[itemCount].ImagePath)' alt="slide-img" data-bgposition='left top' data-bgfit='cover' data-bgrepeat='no-repeat' />

                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
}

Web/Views/Partial/home/HomePageSidebar.cshtml
<div class="custom-slider-wrap">
    <div class="custom-slider-inner">
        <div class="home-custom-slider">
            <div>
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        @for (var itemCount = 0; itemCount < ViewBag.AdvertismentSlider.Count; itemCount++)
                        {
                            <li class="listed-child" data-target="#carousel-example-generic" data-slide-to="@itemCount"></li>
                        }
                    </ol>
                    <div class="carousel-inner">
                        @for (var itemCount = 0; itemCount < ViewBag.AdvertismentSlider.Count; itemCount++)
                        {
                            <div class="item listed-child">
                                <img src="@Url.Content("~" + ViewBag.AdvertismentSlider[itemCount].ImagePath)" alt="@ViewBag.AdvertismentSlider[itemCount].Caption">
                                <div class="carousel-caption">
                                    <span>@ViewBag.AdvertismentSlider[itemCount].Name</span>
                                    <p>@ViewBag.AdvertismentSlider[itemCount].SortDescription</p>
                                </div>
                            </div>
                        }
                    </div>
                    <a class="left carousel-control" href="#" data-slide="prev"> <span class="sr-only">Previous</span> </a> <a class="right carousel-control" href="#" data-slide="next"> <span class="sr-only">Next</span> </a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="hot-deal">
    <ul class="products-grid">
        <li class="right-space two-height item">
            <div class="item-inner">
                <div class="item-img">
                    <div class="item-img-info">
                        <a href="#" title="Retis lapen casen" class="product-image"> <img src="https://via.placeholder.com/800x800" alt="Retis lapen casen"> </a>
                        <div class="hot-label hot-top-left">Hot Deal</div>
                        <div class="box-hover">
                            <ul class="add-to-links">
                                <li><a class="link-quickview" href="quick_view.html"></a></li>
                                <li><a class="link-wishlist" href="wishlist.html"></a></li>
                                <li><a class="link-compare" href="compare.html"></a></li>
                            </ul>
                        </div>
                        <div class="box-timer">
                            <div class="timer-grid countbox_1" data-time="2020/02/01"></div>
                        </div>
                    </div>
                </div>
                <div class="item-info">
                    <div class="info-inner">
                        <div class="item-title"> <a href="product_detail.html" title="Retis lapen casen"> Retis lapen casen </a> </div>
                        <div class="item-content">
                            <div class="rating">
                                <div class="ratings">
                                    <div class="rating-box">
                                        <div class="rating width80"></div>
                                    </div>
                                    <p class="rating-links"> <a href="#">1 Review(s)</a> <span class="separator">|</span> <a href="#">Add Review</a> </p>
                                </div>
                            </div>
                            <div class="item-price">
                                <div class="price-box"> <span class="regular-price"> <span class="price">$125.00</span> </span> </div>
                            </div>
                            <div class="action">
                                <button data-original-title="Add to Cart" title="" type="button" class="button btn-cart"><span>Add to Cart</span> </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </li>
    </ul>
</div>
<div class="testimonials">
    <div class="ts-testimonial-widget">
        <div class="slider-items-products">
            <div id="testimonials-slider" class="product-flexslider hidden-buttons home-testimonials">
                <div class="slider-items slider-width-col4 fadeInUp">
                    @for (var itemCount = 0; itemCount < ViewBag.AdvertismentSlider.Count; itemCount++)
                    {
                        <div class="holder">
                            <div class="thumb"> <img src="@Url.Content("~" + ViewBag.FeedbackSlider[itemCount].ImagePath)" alt="@ViewBag.FeedbackSlider[itemCount].AuthorName)"> </div>
                            <p>@ViewBag.FeedbackSlider[itemCount].SortDescription</p>
                            <div class="line"></div>
                            <strong class="name">@ViewBag.FeedbackSlider[itemCount].AuthorName</strong>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<div class="featured-add-box">
    <div class="featured-add-inner">
        <a href="#"> <img src="https://via.placeholder.com/263x450" alt="f-img"></a>
        <div class="banner-content">
            <div class="banner-text">Women's</div>
            <div class="banner-text1">49% off</div>
            <p>on selected products</p>
            <a href="#" class="view-bnt">Shop now</a>
        </div>
    </div>
</div>

Web/Views/Partial/home/WebSiteFooter.cshtml
@using Web.AppCode;
<div class="footer-middle">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-6">
                <div class="footer-column pull-left">
                    <h4>Quick Links</h4>
                    <ul class="links">
                        <li><a href="@Url.Action("Index", "home")" title="Home">Home</a></li>
                        <li><a href="@Url.Action("Index", "blog")" title="Our News">News</a></li>
                        <li><a href="@Url.Action("question-answer", "agency")" title="FAQs">FAQs</a></li>
                        <li><a href="@Url.Action("privacy-policy", "agency")" title="Privacy Policy">Privacy Policy</a></li>
                        <li><a href="@Url.Action("terms-conditions", "agency")" title="Terms & Conditions">Terms & Conditions</a></li>

                    </ul>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="footer-column pull-left">
                    <h4>Importents</h4>
                    <ul class="links">
                        <li><a title="Student Service" href="@Url.Action("student-service", "agency")">Buy Ticket</a></li>
                        <li><a title="Our News" href="@Url.Action("Index", "blog")">News</a></li>
                        <li><a href="@Url.Action("feedback", "agency")">Feedback</a></li>
                        <li><a href="@Url.Action("our-agents", "agency")">Agents</a></li>
                        @if (LoggedInUserInfoFromCookie.UserDisplayNameInCookie != null && LoggedInUserInfoFromCookie.UserDisplayNameInCookie != "")
                        {
                            <li><a title="Blog" href="@Url.Action("Logout", "account")">Log Out</a> </li>

                        }
                        else
                        {
                            <li><a title="Blog" href="@Url.Action("login", "account")">Agent LogIn</a> </li>
                        }
                    </ul>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <h4>contact us</h4>
                <div class="contacts-info">
                    <address>
                        <i class="add-icon">&nbsp;</i>@ViewBag.SiteSetting.ContactLocation
                    </address>
                    <div class="phone-footer"><i class="phone-icon">&nbsp;</i> @ViewBag.SiteSetting.ContactMobile</div>
                    <div class="email-footer"><i class="email-icon">&nbsp;</i> <a href="#">@ViewBag.SiteSetting.ContactEmailAddress</a></div>
                </div>
            </div>
        </div>
    </div>
</div>